/* eslint:disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JSONSchemaOfProgressData {
    /**
     * Pointer to the schema against which this document should be validated (Schema URL/path)
     */
    $schema?: string
    /**
     * Course name
     */
    course: string
    /**
     * All exercises
     */
    exercises: {
        /**
         * The directory of the exercise
         */
        directory?: string
        /**
         * The number of the exercise
         */
        number: number
        /**
         * The submission part of the exercise
         */
        submission?: {
            /**
             * The achieved points of the exercise
             */
            achievedPoints?: number
            /**
             * The maximum points of the exercise
             */
            points: number
        }
    }[]
    /**
     * Options for progress feedback
     */
    options?: {
        /**
         * If set checks if the given minimum points was achieved over all submissions
         */
        minimumPointsAllSubmissions?: number
        /**
         * If set checks if the given minimum points percentage (0.0 - 1.0) was achieved over all submissions
         */
        minimumPointsPercentageAllSubmissions?: number
        /**
         * If set checks if the given minimum points percentage (0.0 - 1.0) was achieved for each submission
         */
        minimumPointsPercentagePerSubmissions?: number
        /**
         * If set checks if the given minimum points was achieved for each submission
         */
        minimumPointsPerSubmissions?: number
        /**
         * If set checks if the given minimum submission count was achieved over all submissions
         */
        minimumSubmissions?: number
        /**
         * If set checks if the given minimum submission count percentage (0.0 - 1.0) was achieved over all submissions
         */
        minimumSubmissionsPercentage?: number
    }
    /**
     * Name of the progress that is represented by the data
     */
    progressName: string
    /**
     * Version of the progress updater
     */
    version: number
}
