# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  # Run CI when a new branch or tag is created
  create:
    # only run if the tag is a supported version tag
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  # Run CI when a new commit is pushed
  push:
    branches:
      - main
      - dev
  # Run CI when a new pull request is created
  pull_request:
    branches:
      - main
      - dev


jobs:


  # Check if the project can be built without errors
  # Linting, tests and documentation generation is allowed to fail so that in
  # case of an error in them the core build and scripts are still verified
  build:

    strategy:
      matrix:
        node-version: [19.x]
        os: [ubuntu-latest,windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies (npm)
      run: npm ci
    - name: Run tests
      run: npm run test
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Lint circular dependencies
      run: npm run lint:circular
    - name: Create JSON schema
      run: npm run createJsonSchema
    - name: Create bundle
      run: npm run createBundle
    - name: Run other scripts
      run: npm run runExamples
      continue-on-error: true
    - name: Save updateProgress script
      if: matrix.os == 'ubuntu-latest' && (contains(github.head_ref, 'main') || startsWith(github.ref, 'refs/tags/v'))
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-updateProgress
        path: |
          dist/updateProgress.mjs
          progress.schema.json
        retention-days: 7
        if-no-files-found: error


  # Creates a GitHub release if a new tag was pushed
  create-github-release:

    strategy:
      matrix:
        node-version: [19.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    # Only create a GitHub release if a new tag was pushed that starts with v
    # and if the build step was successful
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v3
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
    - name: Create automatic GitHub release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: "${{ github.ref_name }}"
         prerelease: false
         title: "${{ github.ref_name }}"
         files: |
           ${{ matrix.os }}-updateProgress/dist/updateProgress.mjs
           ${{ matrix.os }}-updateProgress/progress.schema.json
