name: Node.js CI

on:
  # Run this for every push and pull request for all branches
  push:
  pull_request:
  # This allows to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-cache-node_modules
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run dist
    - run: npm test
      env:
        CI: true
    - run: npm run examples
    - run: npm run lint
    - run: npm run lintTs
